pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 '
            }
        }
        stage('Lint') {
            steps {
                sh 'pylint src/main/python/calculator.py'
            }
        }
    }
    post {
        always {
            junit 'test-results.xml'
            archiveArtifacts artifacts: '**/test-results.xml', allowEmptyArchive: true
        }
    }
}
