pipeline {
    agent any
    stages {
        // stage('Setup') {
        //     steps {
        //         sh 'pip install -r requirements.txt'
        //     }
        // }
        stage('Test') {
            steps {
                sh 'cd /var/jenkins_home/workspace/python_calculator/python_calculator/src/test/python'
                sh 'python3 test_calculator.py'
            }
        }
        stage('Lint') {
            steps {
                sh 'pylint src/main/python/calculator.py'
            }
        }
    }
    post {
        always {
            junit 'test-results.xml'
            archiveArtifacts artifacts: '**/test-results.xml', allowEmptyArchive: true
        }
    }
}
